### ISSUE TITLE
How to compile iPXE with a new chain link file

### ISSUE THREAD

**Issue by GRIFFCOMMca** [rgl/rpi4-uefi-ipxe#2]
Hi, it appears the iPXE on GitHub is only x86 compatible, so how do we compile another version of iPXE with a new settings and embed chain file?

**Comment by rgl** [comment]
Not sure how that's related to this repository. Essentially you'd need to read the upstream documentation. You can also browse around this repo. You can start at the https://github.com/rgl/rpi4-uefi-ipxe/blob/main/build-ipxe.sh file.
